---
name: Build Artifact

on:
  pull_request:
    types: [closed]
    
jobs:
  merge-PR:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build artifact
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        target: ami.json
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        PACKER_LOG: 1