---
name: Build Artifact

on:
  pull_request:
    types: [closed]
    
jobs:
  merge-PR:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - run: |
          packer build -var-file=vars.json \
        -var 'aws_access_key=${{ secrets.AWS_ACCESS_KEY }}' \
        -var 'aws_secret_key=${{ secrets.AWS_SECRET_KEY }}' \
        -var 'vpc_id=vpc-080d943f60b2174ac' \
        -var 'subnet_id=subnet-0ef9717c66e1d0b7f'\
        -var 'source_ami=ami-09e67e426f25ce0d7' \
        ami.json