---
name: Packer Validate on Pull Requests

on:
  pull_request_target:
    branches: [ main ]

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Validate Packer Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: ami.json
      env:
        PACKER_LOG: 1
